apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sgr-service-spring
  name: sgr-service-spring
spec:
  containers:
  - name: sgr-service-spring
    image: renandpf/sgr-service-spring:1.0.0
    ports:
      - containerPort: 8080
    envFrom:
      - configMapRef:
          name: sgr-service-spring-cm