apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sgr-service-spring-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sgr-service-spring
  template:
    metadata:
      labels:
        app: sgr-service-spring
    spec:
      containers:
      - name: sgr-service-spring
        image: renandpf/sgr-service-spring:1.0.0
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: sgr-service-spring-cm
